/* תחקיר — all UI text in one place. Question labels are NOT here: he owns
   those and edits them inside the app. */
(function (g) {
  'use strict';

  g.T = {
    app: 'תחקיר',

    navHome: 'בית',     capHome: 'HOME',
    navLog: 'טיסות',    capLog: 'LOG',
    navTrends: 'מגמות', capTrends: 'TRENDS',
    navSet: 'הגדרות',   capSet: 'SETUP',

    /* home */
    statusReady: 'מוכן',
    statusBriefed: 'תודרך',
    hDate: 'תאריך',
    briefTitle: 'תדריך',        capBrief: 'BRIEF',
    debriefTitle: 'תחקיר',      capDebrief: 'DEBRIEF',
    newBrief: 'תדריך חדש',
    openBrief: 'השלמת תחקיר',
    briefWaiting: 'תדריך פתוח, ממתין לתחקיר',
    noBriefYet: 'אין תדריך פתוח',
    noBriefHint: 'מלא תדריך לפני הטיסה. הוא יזין את התחקיר אחריה.',
    briefsWaiting: function (n) {
      return n === 1 ? 'תדריך פתוח, ממתין לתחקיר' : n + ' תדריכים ממתינים לתחקיר';
    },
    alsoWaiting: 'ממתינים גם',
    goalsCarried: 'יעדים',
    goalsCarriedHint: 'יעד שלא הושג חוזר בטיסה הבאה מאותה קטגוריה.',
    goalsNextHint: 'היעדים האלה יחכו לטיסה הבאה מאותה קטגוריה.',
    goalsPulled: function (n) {
      return n === 1 ? 'יעד אחד מהטיסה הקודמת נוסף' : n + ' יעדים מהטיסה הקודמת נוספו';
    },
    noGoals: 'אין יעדים פתוחים',
    noGoalsHint: 'יעדים שתגדיר בסוף התחקיר יופיעו כאן.',
    addGoal: 'הוספת יעד',
    recent: 'טיסות אחרונות',
    viewAll: 'הכל',
    noFlights: 'אין עדיין טיסות',
    noFlightsHint: 'הטיסה הראשונה תופיע כאן. הכל נשמר במכשיר הזה בלבד.',

    /* readouts */
    rMinutes: 'דקות',     capMinutes: 'MINUTES',
    rHours: 'שעות טיסה', capHours: 'HOURS',
    rFlights: 'טיסות',    capFlights: 'FLIGHTS',
    rGoals: 'יעדים',      capGoals: 'GOALS MET',
    rWeek: 'השבוע',       capWeek: 'THIS WEEK',
    rSolo: 'אישור לסולו', capSolo: 'SOLO THIS WEEK',

    /* forms */
    save: 'שמירה',
    saveBrief: 'שמירת תדריך',
    saveDebrief: 'שמירת תחקיר',
    saveChanges: 'שמירת שינויים',
    draftSaving: 'AUTOSAVE',
    draftSaved: 'SAVED',
    yourAnswer: 'התשובה שלך',
    fromBrief: 'מהתדריך',
    briefedNote: 'תודרך',
    addExercise: 'הוספת תרגיל',
    addPoint: 'הוספת נקודה',
    pointsAdded: function (n) { return n === 1 ? 'נקודה נוספה' : n + ' נקודות נוספו'; },
    dragHint: 'גרור כדי לסדר מחדש',
    reorder: 'שינוי סדר',
    pasteList: 'הדבקת רשימה',
    pasteListHint: 'הדבק או הקלד את כל הסילבוס, שורה אחת לכל תרגיל. כל שורה תהפוך לתרגיל נפרד עם מקום להערות.',
    exerciseNotes: 'מה קרה בתרגיל הזה',
    exerciseFocus: 'דגשים לתרגיל',
    loadSyllabus: 'טעינה מהסילבוס',
    noSyllabusFor: function (s) { return '"' + s + '" לא נמצאה בסילבוס. אפשר להוסיף תרגילים ידנית.'; },
    syllabusFilled: function (n) { return n + ' תרגילים נטענו מהסילבוס'; },
    replaceSyllabus: 'להחליף את הסילבוס הקיים?',
    replaceSyllabusBody: 'התרגילים שכתבת יוחלפו בתרגילים מהסילבוס של הגיחה הזו.',
    goalMet: 'הושג',
    goalMissed: 'לא הושג',
    minutesUnit: 'דק׳',
    editBrief: 'עריכת התדריך',

    /* the two-stage loop, explained once, on an empty home screen */
    startTitle: 'איך זה עובד',
    startB1: 'לפני הטיסה ממלאים תדריך: נושא, יעדים, וסילבוס.',
    startB2: 'מקלידים את הגיחה ("AW 3") והתרגילים מהסילבוס נטענים לבד.',
    startB3: 'אחרי הנחיתה משלימים תחקיר. יעד שלא הושג חוזר לטיסה הבאה מאותה קטגוריה.',
    startGo: 'נתחיל',

    /* backup */
    backupNow: 'ייצוא גיבוי',
    backupHomeTitle: 'הטיסות שלך קיימות רק בטלפון הזה.',
    backupHomeBody: 'ייצא קובץ גיבוי ושמור אותו איפשהו. לוקח שתי שניות.',

    /* drafts */
    draftRestored: 'שוחזרה טיוטה שלא נשמרה',
    draftBadge: 'טיוטה',
    draftDiscard: 'התחלה מחדש',
    draftDiscardBody: 'הטיוטה תימחק והטופס יחזור למה שנשמר.',

    /* log */
    search: 'חיפוש בכל התשובות',
    searchSyllabus: 'חיפוש גיחה או תרגיל',
    selectAllShown: 'בחר את המוצגים',
    noMatches: 'אין תוצאות',
    noMatchesHint: 'נסה מילה אחרת או נקה את הסינון.',
    all: 'הכל',
    categories: 'קטגוריות',
    carriedToNext: 'עבר ליעדים לטיסה הבאה',
    awaiting: 'ממתין לתחקיר',

    /* weekly summary */
    selectMode: 'בחירה ידנית',
    weekSummary: 'סיכום השבוע',
    nThisWeek: function (n) { return n === 1 ? 'טיסה אחת השבוע' : n + ' טיסות השבוע'; },
    noneThisWeek: 'אין טיסות השבוע',
    pickManually: 'בחירה ידנית של טיסות',
    selectWeek: 'בחר את השבוע',
    clearSel: 'ניקוי',
    nSelected: function (n) { return n + ' נבחרו'; },
    makeSummary: 'יצירת סיכום',
    summary: 'סיכום',
    summaryTitle: 'סיכום שבועי',
    summaryCustom: 'סיכום טיסות',
    summaryOf: function (a, b) { return a + ' עד ' + b; },
    summaryStats: function (f, m) { return f + ' טיסות · ' + m + ' דקות'; },
    docStats: function (f, h) { return f + ' טיסות · ' + h + ' שעות'; },
    docSolo: function (a, b) { return 'אישור לסולו ' + a + '/' + b; },
    alsoFlown: 'גם: ',
    secGoals: 'יעדים',
    goalsMet: 'הושגו',
    goalsMissed: 'לא הושגו',
    secRepeatGoals: 'יעדים שחוזרים על עצמם',
    secFocus: 'דגשים שחזרו',
    secExercises: 'תרגילים שבוצעו',
    secPoints: 'נקודות עיקריות',
    secSafety: 'בטיחות',
    secFlights: 'פירוט הטיסות',
    timesN: function (n) { return n === 1 ? 'פעם אחת' : n + ' פעמים'; },
    inNFlights: function (n) { return 'ב־' + n + ' טיסות'; },
    recurringTag: 'חוזר',
    noneSelected: 'לא נבחרו טיסות',
    noneSelectedHint: 'סמן את הטיסות שתרצה לסכם ולחץ יצירת סיכום.',
    copyDoc: 'העתקה למסמך',
    exportDoc: 'ייצוא כמסמך',
    docHint: 'הקובץ נפתח ב־Google Docs. אפשר גם להעתיק ולהדביק ישירות למסמך חדש.',
    copiedDoc: 'הועתק, אפשר להדביק ל־Google Docs',

    /* detail */
    copyText: 'העתקה כטקסט',
    deleteFlight: 'מחיקת הטיסה',
    notAnswered: 'לא נענה',
    share: 'שיתוף',
    edit: 'עריכה',

    /* trends */
    trendsEmpty: 'אין עדיין מה להראות',
    trendsEmptyHint: 'אחרי כמה תחקירים יופיע כאן מה חוזר על עצמו.',
    flightsPerWeek: 'טיסות לשבוע',
    lastWeeks: '8 השבועות האחרונים',
    goalRate: 'עמידה ביעדים',
    repeatedGoals: 'יעדים שחוזרים',
    missedGoals: 'יעדים שלא הושגו',
    readAcross: 'תשובה אחת לאורך כל הטיסות',
    nothingHere: 'עדיין לא נכתב כאן דבר.',
    totalMinutes: 'שעות מתועדות',

    /* syllabus progress */
    sylProgress: 'התקדמות בסילבוס',
    sylDone: function (a, b) { return a + ' מתוך ' + b + ' גיחות'; },
    sylNext: 'הבא בתור',
    sylNextNone: 'סיימת את כל הגיחות שבסילבוס.',
    sylFlown: 'בוצעה',
    sylOpenChart: 'הסילבוס המלא',
    sylNoneYet: 'עוד לא נרשמה גיחה שמופיעה בסילבוס.',

    /* instructors */
    byInstructor: 'לפי מדריך',
    instFlights: function (n) { return n === 1 ? 'טיסה אחת' : n + ' טיסות'; },
    instSeeAll: 'הצג את הטיסות',
    instNone: 'לא נרשם מדריך באף טיסה.',

    /* settings */
    settings: 'הגדרות',
    appearance: 'מראה',
    themeDark: 'לילה', themeLight: 'יום', themeAuto: 'אוטומטי',
    questions: 'שאלות',
    questionsHint: 'הוספה, שינוי שם, סידור ומחיקה. השינויים חלים על הטיסה הבאה.',
    stageBrief: 'תדריך', stageDebrief: 'תחקיר',
    addQuestion: 'הוספת שאלה',
    editQuestion: 'עריכת שאלה',
    qLabel: 'שם השאלה',
    qType: 'סוג תשובה',
    qStage: 'באיזה טופס',
    qOptions: 'אפשרויות',
    qOptionsHint: 'אפשרות אחת בכל שורה',
    qInDebrief: 'בתחקיר',
    qInEdit: 'ניתן לעריכה',
    qInReadonly: 'לקריאה בלבד',
    qInNone: 'לא מופיע',
    lockedQuestion: 'שאלת מערכת. אפשר לשנות שם, אי אפשר למחוק.',
    moveUp: 'העלאה', moveDown: 'הורדה',
    restoreDefaults: 'שחזור ברירת המחדל',
    syllabusRef: 'סילבוס האימונים',
    syllabusRefSub: function (n) { return n ? n + ' גיחות' : 'עדיין לא נטען'; },
    syllabusRefEmpty: 'הסילבוס עדיין לא נטען',
    syllabusRefEmptyHint: 'כשהטבלה תיטען, כל גיחה תופיע כאן והתרגילים שלה ייכנסו לתדריך אוטומטית.',
    yourData: 'המידע שלך',
    exportCsv: 'ייצוא לגיליון', exportCsvSub: 'CSV',
    exportJson: 'ייצוא גיבוי', exportJsonSub: 'JSON, משחזר הכל',
    importJson: 'שחזור מגיבוי', importJsonSub: 'מתמזג עם מה שקיים',
    privacy: 'פרטיות',
    setCode: 'הגדרת קוד כניסה', changeCode: 'שינוי קוד הכניסה', removeCode: 'ביטול קוד הכניסה',
    codeOn: 'פעיל', codeOff: 'כבוי', needsHttps: 'דורש כתובת מאובטחת',
    privacyNote: 'לאפליקציה אין חשבון ואין שרת. שום דבר שנכתב כאן לא יוצא מהמכשיר. ' +
                 'קוד הכניסה מונע ממישהו שמרים את הטלפון לקרוא, אבל הוא לא מצפין את הקובץ.',
    deleteAll: 'מחיקת כל הטיסות',
    cannotUndo: 'לא ניתן לשחזר',
    offline: 'עובד גם בלי רשת',
    onDevice: 'טיסות במכשיר',

    backupTitle: 'כדאי לגבות.',
    backupNever: 'עוד לא ייצאת גיבוי.',
    backupDays: function (n) { return 'הגיבוי האחרון היה לפני ' + n + ' ימים.'; },
    backupBody: 'הכל קיים רק בטלפון הזה. ייצא קובץ ושמור אותו במקום בטוח.',

    installTitle: 'הוספה למסך הבית',
    installBodyIOS: 'לחץ על כפתור השיתוף ואז "הוסף למסך הבית". האפליקציה תיפתח במסך מלא ותעבוד גם בלי קליטה.',
    installBodyAndroid: 'פתח את תפריט שלוש הנקודות ובחר "התקנת אפליקציה". היא תיפתח במסך מלא ותעבוד גם בלי קליטה.',
    installBodyGeneric: 'הוסף את האפליקציה למסך הבית. היא תיפתח במסך מלא ותעבוד גם בלי קליטה.',
    installNow: 'התקנה',
    installedToast: 'נוספה למסך הבית',
    gotIt: 'הבנתי',

    /* undo */
    undo: 'החזרה',
    restoredToast: 'הטיסה הוחזרה',
    sessionStale: 'לא היה אפשר לאמת מול Google בלי רשת. תתבקש להיכנס שוב כשתהיה קליטה.',

    /* google sign-in gate */
    gateBody: 'האפליקציה פתוחה רק לחשבונות מאושרים.',
    gateSignIn: 'כניסה עם Google',
    gateChecking: 'בודק…',
    gateDenied: function (e) { return 'החשבון ' + e + ' לא מאושר לאפליקציה הזו.'; },
    gateDeniedNote: 'אפשר לנסות עם חשבון אחר.',
    gateOther: 'חשבון אחר',
    gateFailed: 'ההתחברות לא הושלמה.',
    gateRetry: 'נסה שוב',
    gateOffline: 'צריך חיבור לרשת רק בהתחברות הראשונה. אחר כך האפליקציה נפתחת גם בלי קליטה.',
    gateNoNet: 'אין חיבור לרשת כרגע.',
    account: 'חשבון',
    signedInAs: function (e) { return 'מחובר כ־' + e; },
    signOut: 'התנתקות',
    confirmSignOut: 'להתנתק?',
    confirmSignOutBody: 'הטיסות נשארות במכשיר. תצטרך להיכנס שוב עם Google כדי לפתוח את האפליקציה.',

    /* course selection */
    courseTitle: 'שלב ההכשרה',
    coursePrompt: 'באיזה שלב אתה נמצא?',
    courseBody: 'הבחירה קובעת את הסילבוס, קטגוריות הטיסה והיעדים המומלצים שיוצגו לך.',
    courseConfirm: 'אישור',
    courseSuggested: 'זוהה עבורך',
    courseChangeable: 'ניתן לשנות בכל עת בהגדרות.',
    courseSection: 'שלב ההכשרה',
    courseCurrent: function (n) { return 'קורס ' + n; },
    courseChange: 'שינוי שלב הכשרה',
    courseChangeTitle: function (n) { return 'לעבור לקורס ' + n + '?'; },
    courseChangeBody: 'הסילבוס והקטגוריות יתחלפו. הטיסות שכבר רשומות נשמרות כמו שהן ' +
                      'ונשארות משויכות לקורס שבו בוצעו.',
    courseSwitched: function (n) { return 'עברת לקורס ' + n; },
    courseTag: function (n) { return 'קורס ' + n; },
    courseSyllabusCount: function (n, c) { return n + ' גיחות · קורס ' + c; },

    /* syllabus suggestions */
    simBadge: 'מאמן',
    simHint: 'גיחת מאמן. קיימת גם גיחה באוויר באותו מספר.',
    pickGicha: 'איזו גיחה?',
    pickGichaBody: 'יש כמה גיחות בשם הזה. בחר את הנכונה כדי לטעון את הסילבוס שלה.',
    pickedGicha: 'יש כמה גיחות בשם הזה. נטענה המסתברת ביותר, אפשר להחליף בלחיצה.',
    suggestedGoals: 'יעדים מומלצים מהסילבוס',
    goalsSuggested: function (n) { return n === 1 ? 'יעד מומלץ נוסף' : n + ' יעדים מומלצים נוספו'; },
    plannedMinutes: function (n) { return 'משך מתוכנן ' + n + ' דק׳'; },
    gichaNote: 'הערות לגיחה',
    gichaInstNote: 'הערות למאמן',

    enterCode: 'הזן את הקוד',
    wrongCode: 'קוד שגוי',
    chooseCode: 'בחר קוד בן 4 ספרות',
    repeatCode: 'הזן שוב',
    codeMismatch: 'הקודים לא תואמים. נסה שוב.',
    codeOnToast: 'קוד הכניסה הופעל',
    codeOffToast: 'קוד הכניסה בוטל',
    codeFailed: 'לא ניתן להגדיר קוד כאן',

    cancel: 'ביטול', confirm: 'אישור', add: 'הוספה', remove: 'הסרה', delete: 'מחיקה',
    today: 'היום', yesterday: 'אתמול',
    daysAgo: function (n) { return 'לפני ' + n + ' ימים'; },
    savedToast: 'נשמר',
    briefSavedToast: 'התדריך נשמר',
    debriefSavedToast: 'התחקיר נשמר',
    deletedToast: 'נמחק',
    copiedToast: 'הועתק',
    needSomething: 'מלא לפחות שדה אחד לפני שמירה',

    typeText: 'שורה', typeTextarea: 'טקסט', typeChoice: 'בחירה',
    typeNumber: 'מספר', typeMinutes: 'דקות', typeDate: 'תאריך',
    typeGoals: 'יעדים', typeSyllabus: 'סילבוס', typeList: 'רשימה',

    confirmDeleteFlight: function (d) { return 'למחוק את הטיסה מ־' + d + '?'; },
    confirmDeleteBody: 'הטיסה תימחק מהמכשיר הזה. לא ניתן לשחזר.',
    confirmDeleteAll: function (n) { return 'למחוק את כל ' + n + ' הטיסות?'; },
    confirmDeleteAllBody: 'הכל יימחק מהמכשיר. ייצא גיבוי קודם אם יש סיכוי שתרצה את זה בעתיד.',
    confirmDeleteQuestion: function (q) { return 'למחוק את "' + q + '"?'; },
    confirmDeleteQuestionBody: 'השאלה לא תופיע בטפסים חדשים. תשובות קיימות יישמרו ויוצגו בטיסות הישנות.',
    confirmCodeOff: 'לבטל את קוד הכניסה?',
    confirmCodeOffBody: 'כל מי שירים את הטלפון יוכל לפתוח את האפליקציה.'
  };
  Object.assign(g.T, {
    notebook: 'מחברת', notebookTitle: 'המחברת שלי', notebookSub: 'מקום למחשבות, תובנות וכל מה שכדאי לזכור.',
    noteNew: 'עמוד חדש', noteUntitled: 'ללא כותרת', noteTitle: 'כותרת העמוד', noteBody: 'מה חשוב לך לזכור?',
    noteInbox: 'ללא תיקייה', noteAll: 'כל העמודים', noteSearch: 'חיפוש במחברת', noteEmpty: 'העמוד הראשון מחכה לך',
    noteEmptyBody: 'אפשר להתחיל ממחשבה קצרה. הטקסט נשמר במכשיר ונכלל בגיבוי.',
    noteFolders: 'תיקיות במחברת', noteFolder: 'תיקייה',
    back: 'חזרה', skipContent: 'דילוג לתוכן',
    reportTitle: 'סיכום טיסות למדריך', reportEyebrow: 'מבט שבועי',
    reportIntro: 'הישגים, נושאים להמשך והתיעוד שמאחוריהם.', reportPeriod: 'תקופה וטיסות בדוח',
    reportThisWeek: 'השבוע', reportLastWeek: 'השבוע הקודם', reportApply: 'עדכון הדוח',
    reportManual: 'בחירת טיסות מהיומן', reportRangeInvalid: 'יש לבחור תאריכים תקינים. תאריך הסיום צריך להיות אחרי תאריך ההתחלה או באותו יום.',
    reportUnassigned: 'ללא שיוך לקורס', reportGoalsRate: 'השגת יעדים', reportNoGrade: 'אין הערכה', reportNotGraded: 'לא הוערך',
    reportGraded: function (met, total, open) { return met + ' מתוך ' + total + ' יעדים שהוערכו הושגו' + (open ? ' · ' + open + ' יעדים ללא הערכה' : ''); },
    reportMissingMinutes: function (n) { return 'ב־' + n + ' טיסות לא הוזן משך. הסכום כולל רק דקות שתועדו.'; },
    reportNext: 'יעדים שנקבעו להמשך', reportNextHint: 'כפי שנכתבו בתחקירים שבדוח. ייתכן שחלה התקדמות נוספת מאז.',
    reportLaterMet: 'הושג בהמשך התקופה', reportNoSafety: 'לא נכתבו הערות בטיחות בטיסות שנבחרו. אין בכך אישור שלא היו אירועים.',
    reportBasis: 'הדוח מבוסס על טיסות שתוחקרו ועל הטקסט שנשמר ביומן. תרגיל ללא הערת תחקיר אינו מסומן כתרגיל שבוצע.',
    reportBriefFocus: 'דגש מהתדריך', reportCadet: 'צוער', reportIncludeIdentity: 'צירוף השם והכינוי מהפרופיל לדוח',
    reportPrint: 'הדפסה או שמירה כ־PDF', reportPrintBlocked: 'הדפדפן חסם את פתיחת הדוח. אפשר להוריד קובץ או להעתיק את התוכן.',
    reportCopyFailed: 'ההעתקה לא הצליחה. אפשר להוריד את הדוח כקובץ.',
    reportExportHint: 'הקובץ כולל את התוכן המוצג לפי רמת הפירוט שבחרת, לרבות שמות מדריכים והערות הטיסה.',
    reportSources: 'הטיסות שבהן תועד', reportNoGoals: 'לא תועדו הערכות יעד בתקופה הזאת.',
    reportNoExerciseNote: 'אין הערת תחקיר לתרגיל הזה.', reportOpenFlight: 'פתיחת התחקיר המלא',
    reportPreview: 'תצוגה מקדימה של הדוח', closeReport: 'חזרה לסיכום',
    reportEmpty: 'אין טיסות מתוחקרות בבחירה הזאת', reportEmptyHint: 'אפשר לבחור שבוע אחר, לשנות את התאריכים או לבחור טיסות מהיומן.',
    reportShortHint: 'עיקרי התקופה', reportFullHint: 'כולל פירוט לכל טיסה', reportDetails: 'התיעוד לפי טיסה',
    themeCalm: 'לילה שקט', themeDarkHint: 'תא טייס בגווני כחול', themeCalmHint: 'פחם ומרווה, ללא זוהר',
    themeLightHint: 'בהיר וקריא באור יום', themeAutoHint: 'לפי הגדרות המכשיר',
    pilotProfile: 'הפרופיל שלי', pilotProfileSub: 'השם, הכינוי והדגש האישי שלך.',
    pilotProfileHint: 'כל השדות לבחירתך. הפרטים נשמרים במכשיר ובגיבוי, ולא מצורפים אוטומטית למשוב או לשיתוף.',
    pilotName: 'שם לתצוגה', pilotCallsign: 'כינוי אישי', pilotCallsignHint: 'אם יש כינוי שנוח לך להשתמש בו.',
    pilotFocus: 'הדגש שלי לתקופה הקרובה', pilotFocusPlaceholder: 'משהו אחד שחשוב לך לקדם',
    profileSaved: 'הפרופיל נשמר', personalizeProfile: 'התאמה אישית',
    pilotJournal: 'יומן הטיסה האישי', pilotGreeting: function (name) { return name ? 'שלום, ' + name : 'היומן שלך'; },
    focusPrompt: 'בחירת דגש אישי לתקופה הקרובה', recordedCoverage: 'התקדמות לפי התיעוד שלך',
    journalOverview: 'התמונה שלך עד עכשיו', allJournalData: 'כל הטיסות המתוחקרות ביומן',
    recordedGoals: function (met, total) { return met + ' מתוך ' + total + ' יעדים שהוערכו'; },
    noGradedGoals: 'עדיין אין יעדים שהוערכו', flightLogTitle: 'יומן הטיסות', flightLogSub: 'כל תדריך, תחקיר ותובנה. במקום אחד.',
    trendsTitle: 'המבט לאורך הדרך', trendsSub: 'מה התקדם ומה כדאי לקחת לטיסה הבאה.',
    settingsSub: 'המרחב שלך, בדרך שנוחה לך.', trainingTools: 'כלים לדרך',
    questionEditor: 'התאמת שאלות התדריך והתחקיר', questionCount: function (n) { return n + ' שאלות פעילות'; },
    briefStep: 'לפני הטיסה', debriefStep: 'אחרי הטיסה', workflowLabel: 'שלבי תיעוד הטיסה',
    syllabusSub: 'איתור גיחות ותרגילים לפי פרקי הקורס.', clearFilters: 'ניקוי הסינון',
    activeFilters: function (n) { return 'סינון טיסות · ' + n + ' פעילים'; },
    weekChartLabel: function (date, n) { return 'השבוע שמתחיל ב־' + date + ': ' + n + ' טיסות'; },
    goalText: 'נוסח היעד', exerciseText: 'שם התרגיל', pointText: 'נקודה עיקרית',
    closeFolders: 'סגירת התיקיות', folderOptions: 'אפשרויות התיקייה', noteOptions: 'אפשרויות העמוד',
    noteCount: function (n) { return n === 1 ? 'עמוד אחד' : n + ' עמודים'; },
    noteSearchEmpty: 'לא נמצאו עמודים', noteSearchEmptyBody: 'אפשר לנסות מילה אחרת או לבחור תיקייה אחרת.',
    folderNew: 'תיקייה חדשה', folderName: 'שם התיקייה', folderRename: 'שינוי שם התיקייה', folderDelete: 'מחיקת תיקייה',
    folderDeleteBody: 'העמודים יועברו ל״ללא תיקייה״. התוכן שלהם יישמר.',
    priority: 'עדיפות', priorities: ['רגילה', 'חשובה', 'דחופה'], pinNote: 'נעיצה בראש המחברת', unpinNote: 'ביטול נעיצה',
    noteDelete: 'העברה לנמחקו לאחרונה', noteDeleted: 'העמוד הועבר לנמחקו לאחרונה',
    onDeviceOnly: 'נשמר במכשיר הזה ונכלל בגיבוי JSON. אין סנכרון בין מכשירים.',
    courseProgress: 'הדרך שלי בקורס', progressSub: 'כל גיחה מתועדת היא עוד צעד בדרך.',
    progressCount: function (n, total) { return n + ' מתוך ' + total + ' גיחות בסילבוס'; },
    progressBasis: 'לפי גיחות שהושלמו ותועדו בקורס הנבחר. זהו מעקב אישי, לא אישור רשמי לסיום הקורס.',
    progressUnknown: function (n) { return n + ' טיסות ללא שיוך קורס אינן נכללות בחישוב.'; },
    progressRemaining: 'עוד בדרך', progressCompleted: 'תועדו והושלמו', progressSections: 'פרקי הסילבוס',
    progressNext: 'הגיחה הבאה שטרם תועדה', milestones: 'אבני הדרך שלי', milestoneAdd: 'אבן דרך חדשה',
    milestoneTitle: 'שם אבן הדרך', milestoneDate: 'תאריך מתוכנן, לא חובה', milestoneTarget: 'יעד של גיחות שהושלמו, לא חובה',
    milestoneDone: 'הושלמה', milestoneShare: 'לכלול בכרטיס השיתוף', milestoneEmpty: 'צ׳ק, לילה מיוחד או יעד אישי. הוסף את התאריך כשיהיה ידוע.',
    milestonePersonal: 'אבן דרך אישית', shareProgress: 'שיתוף ההתקדמות', sharePreview: 'תצוגה לפני שיתוף',
    shareProgressHint: 'הכרטיס כולל אחוז התקדמות ואבני דרך שבחרת לשתף. הוא אינו כולל תשובות, שמות מדריכים או תוכן מהמחברת.',
    shareImage: 'שיתוף הכרטיס', downloadImage: 'שמירת תמונה', copySummary: 'העתקת סיכום', shareFailed: 'לא ניתן לשתף כרגע. אפשר לשמור את התמונה.',
    shareCaption: function (course, pct, n, total) { return 'הדרך שלי בקורס ' + course + ': ' + pct + '% מהסילבוס תועדו, ' + n + ' מתוך ' + total + ' גיחות. מעקב אישי בתחקיר.'; },
    feedback: 'שליחת משוב', feedbackSub: 'נתקלת בתקלה או חשבת על שיפור? אפשר לכתוב כאן.',
    feedbackTypes: ['דיווח על תקלה', 'הצעה לשיפור', 'אחר'], feedbackKind: 'סוג המשוב', feedbackMessage: 'מה תרצה לשתף?',
    feedbackContact: 'כתובת לחזרה, לא חובה', feedbackSend: 'שליחת המשוב', feedbackSending: 'שולח…',
    feedbackSent: 'המשוב נשלח. תודה שעזרת לשפר את תחקיר.', feedbackFailed: 'המשוב לא נשלח. הטקסט נשמר ואפשר לנסות שוב.',
    feedbackOffline: 'אין חיבור לרשת. המשוב נשמר כטיוטה. אפשר לנסות לשלוח כשיהיה חיבור.',
    feedbackPrivacy: 'נשלחים רק המשוב, כתובת החזרה שהזנת ופרטי האבחון שבחרת. הטיסות והמחברת אינם מצורפים.',
    feedbackDiagnostics: 'צירוף גרסת האפליקציה, סוג המכשיר והקורס לצורך בדיקה',
    feedbackNotReady: 'שירות המשוב עדיין בהכנה. אפשר לכתוב ולשמור טיוטה.', feedbackLength: 'יש לכתוב בין 5 ל־5000 תווים.',
    feedbackSaved: 'טיוטת המשוב נשמרה', whatsNew: 'מה חדש בתחקיר', releaseIntro: 'עיצוב חדש, שעות הטיסה שלך במבט אחד ושליטה מלאה בהגדרות. כל מה ששמרת עבר איתך.',
    releaseItems: [
      ['עיצוב חדש ומסך בית חכם', 'שעות הטיסה, קצב השבוע, היעדים והסולו מופיעים ראשונים, עם מספרים מתגלגלים וגרף טיסות של השבועות האחרונים.'],
      ['שליטה מלאה בהגדרות', 'עדכון ידני של סך שעות הטיסה, בחירת רמת האנימציות והרטט, ובחירה מה יופיע במסך הבית.'],
      ['תחקיר אישי יותר', 'שם, כינוי ודגש אישי לבחירתך. מסך הבית מציג קודם את התחקירים שממתינים ואת הדרך שלך בקורס.'],
      ['לילה שקט ועיצוב נוח יותר', 'ערכת נושא כהה ורכה, תמונות תעופה מקוריות, טקסט קריא יותר וכפתורים נוחים.'],
      ['מחברת במרחק נגיעה', 'עמודים, תיקיות, חיפוש ועדיפויות. אפשר לפתוח אותה מכל מסך.'],
      ['הדרך שלך בקורס', 'התקדמות לפי הסילבוס, אבני דרך אישיות וכרטיס לשיתוף עם המשפחה והחברים.'],
      ['שמירה ושחזור', 'גיבוי מלא יותר, שחזור עם תצוגה מקדימה, טיוטות נשמרות ופריטים שנמחקו ניתנים לשחזור.'],
      ['תדריך, תחקיר ודוח למדריך', 'תיקונים בהעברת יעדים ובהזנת דקות. סיכום עם בחירת תקופה, יעדים להמשך, תצוגה מקדימה וייצוא להדפסה.'],
      ['המשוב שלך', 'מסך משוב חדש בהגדרות, עם שמירת טיוטה גם ללא חיבור.']
    ],
    understood: 'הבנתי', previewBuild: 'גרסת תצוגה מקדימה', backupRecovery: 'גיבוי ושחזור',
    backupRecoveryBody: 'הכניסה עם Google אינה מגבה את הנתונים. גיבוי JSON כולל טיסות, שאלות, יעדים, טיוטות, מחברת ואבני דרך.',
    recovery: 'שחזור ופריטים שנמחקו', recentlyDeleted: 'נמחקו לאחרונה', recoveryDrafts: 'טיוטות שמורות',
    recoveryEmpty: 'אין פריטים לשחזור', restore: 'שחזור', restored: 'שוחזר', recoveryCopy: 'הורדת עותק השחזור האחרון',
    archivedQuestions: 'שאלות בארכיון', archiveRestore: 'החזרת השאלה לטפסים', recoveryRaw: 'הורדת נתונים לבדיקה',
    saveFailed: 'השמירה לא הושלמה', saveFailedBody: 'לא ניתן לשמור במכשיר כרגע. הטקסט נשאר כאן. נסה שוב או ייצא גיבוי.',
    draftConflict: 'נמצאו שתי גרסאות', draftConflictBody: 'יש טיוטה וגם שינוי שנשמר אחריה. בחר איזו גרסה לפתוח. עותק לשחזור יישמר לפני ההחלפה.',
    useSaved: 'פתיחת הגרסה השמורה', useDraft: 'פתיחת הטיוטה', reorderKeys: 'שינוי סדר. השתמש בחצים למעלה ולמטה.',
    importPreview: 'בדיקה לפני שחזור', importCounts: function (p) { return p.added + ' טיסות חדשות, ' + p.updated + ' עדכונים, ' + p.goals + ' יעדים, ' + p.drafts + ' טיוטות ו־' + p.notes + ' עמודים במחברת.'; },
    importPreferences: 'שחזור הגדרות ושינויים בשאלות מתוך הגיבוי',
    importMergeHint: 'טיסות חדשות יותר נשמרות. תוכן קיים שאינו בגיבוי לא נמחק. לפני השחזור נשמר עותק מקומי לחזרה.',
    importComplete: function (r) { return r.added + ' טיסות נוספו, ' + r.updated + ' עודכנו'; },
    importInvalid: 'הקובץ אינו גיבוי תקין. לא בוצע שינוי.', importFailed: 'השחזור לא הושלם. עותק המצב הקודם זמין במסך השחזור.',
    questionVersionHint: 'שינוי סוג של שאלה שכבר נענתה ייצור גרסה חדשה לטפסים הבאים. התשובות הישנות נשמרות.',
    advancedSettings: 'ניהול מתקדם', logFilters: 'סינון טיסות', allCourses: 'כל הקורסים', allStages: 'כל המצבים',
    completedOnly: 'תוחקרו', pendingOnly: 'ממתינות לתחקיר', fromDate: 'מתאריך', toDate: 'עד תאריך', instructorFilter: 'סינון לפי מדריך',
    summaryFull: 'סיכום מלא', summaryShort: 'סיכום קצר', summaryCompletedOnly: 'הסיכום כולל טיסות שתוחקרו בלבד.',
    resumeDraft: 'חזרה לטיוטה', updateReady: 'עדכון מוכן. אפשר להמשיך לכתוב ולעדכן לאחר השמירה.', updateNow: 'פתיחת הגרסה החדשה',
    startupError: 'לא ניתן לפתוח את הנתונים כרגע', startupErrorBody: 'הנתונים לא נמחקו. אפשר לטעון מחדש או להוריד עותק לבדיקה.',
    actionFailed: 'הפעולה לא הושלמה. אפשר לנסות שוב.',
    pickFlight: 'בחירת גיחה מהסילבוס',
    goalHistoryHint: 'הופעות של אותו נוסח יעד בטיסות שבסינון. אפשר לפתוח כל טיסה לפרטים.',
    courseLabel: 'קורס', unknownCourse: 'קורס לא משויך',
    rawRecovery: 'הורדת עותק גולמי לבדיקה',
    privacyNote: 'הטיסות והמחברת נשמרות במכשיר. הכניסה עם Google אינה גיבוי ואינה סנכרון. מידע יוצא מהמכשיר רק בייצוא, בשיתוף או בשליחת משוב שבחרת לשלוח. קוד הנעילה אינו מצפין את הנתונים.',
    feedbackFailed: 'לא התקבל אישור לשליחה. הטקסט נשמר. ייתכן שהמשוב כבר התקבל; ניסיון נוסף עלול לשלוח עותק נוסף.',
    downloadNote: 'הורדת העמוד', saveSeparateCopy: 'שמירת הכתיבה כעותק נפרד',
    catalogueCheckpoints: 'נקודות ציון בסילבוס', catalogueCheckpointsHint: 'הגיחה הראשונה המופיעה בסילבוס בכל סוג. מועדים ואירועים נוספים אפשר להוסיף כאבני דרך אישיות.',
    checkpointSolo: 'סולו בסילבוס', checkpointNight: 'לילה בסילבוס', checkpointLogged: 'תועדה', checkpointPending: 'טרם תועדה',
    releaseDetails: 'לכל השינויים', documentedExercises: 'תרגילים עם הערות תחקיר',
    plannedExercises: 'תרגילים שתוכננו ללא הערות תחקיר: ',
    retry: 'ניסיון נוסף', draftSaving: 'שומר…', draftSaved: 'הטיוטה נשמרה',
    exportJsonSub: 'גיבוי מלא, כולל המחברת והטיוטות',
    confirmDeleteBody: 'הטיסה תועבר לנמחקו לאחרונה ותהיה זמינה לשחזור.',
    confirmDeleteAllBody: 'הטיסות יועברו לנמחקו לאחרונה ויישמר עותק מקומי לשחזור. מומלץ לייצא גיבוי קודם.',
    greeting: function (hour, name) {
      var part = hour >= 5 && hour < 12 ? 'בוקר טוב' : hour >= 12 && hour < 17 ? 'צהריים טובים' : hour >= 17 && hour < 22 ? 'ערב טוב' : 'לילה טוב';
      return name ? part + ', ' + name : part;
    },
    nextStep: 'הצעד הבא', nextFlight: 'הטיסה הבאה',
    nextFlightGoals: function (n) { return n === 1 ? 'יעד אחד מחכה לתדריך הבא.' : n + ' יעדים מחכים לתדריך הבא.'; },
    nextFlightHint: 'לפני הטיסה ממלאים תדריך קצר. אחרי הנחיתה משלימים אותו לתחקיר.',
    draftInProgress: 'תדריך שעוד לא נשמר', continueBrief: 'המשך התדריך', draftUntitled: 'עוד בלי נושא',
    goalsOpenTitle: 'יעדים פתוחים', lastEightWeeks: '8 שבועות',
    detailBrief: 'לפני הטיסה', detailDebrief: 'אחרי הטיסה', moreActions: 'פעולות נוספות',
    courseRouteHint: 'כל נקודת ציון היא פרק בסילבוס, במספור של הרשימה למטה. אורך כל רגל לפי מספר הגיחות בפרק.',
    courseRouteLabel: function (pct, next) { return 'מפת המסלול בקורס: ' + pct + '% מהגיחות תועדו' + (next ? '. הפרק הבא: ' + next : ''); },
    hoursUnit: 'שעות', minutesShort: 'דק׳', flightsN: function (n) { return n === 1 ? 'טיסה אחת' : n + ' טיסות'; },
    quickActions: 'קיצורי דרך', qaRoute: 'המסלול', qaSyllabus: 'סילבוס', qaWeek: 'סיכום שבוע', qaBackup: 'גיבוי',
    myProfile: 'הפרופיל שלי',
    trailLabel: function (counts) { return 'טיסות מתוחקרות בכל אחד משמונת השבועות האחרונים, מהישן לחדש: ' + counts.join(', '); },

    /* the course's end date */
    courseEnds: 'סיום הקורס',
    courseEndsOn: function (d) { return 'סיום הקורס ' + d; },
    daysLeftN: function (n) { return n === 1 ? 'עוד יום אחד' : 'עוד ' + n + ' ימים'; },
    daysLeftLabel: function (n) { return n === 1 ? 'יום לסיום הקורס' : 'ימים לסיום הקורס'; },
    courseLastDay: 'היום הוא היום האחרון בקורס', courseEnded: function (d) { return 'הקורס הסתיים ב־' + d; },
    sortiesUndocumented: function (n) { return n === 1 ? 'גיחה אחת בסילבוס עוד לא תועדה' : n + ' גיחות בסילבוס עוד לא תועדו'; },
    paceToFinish: function (n) { return 'כדי שכל הסילבוס יתועד עד הסיום: כ־' + n + ' ' + (n === 1 ? 'גיחה' : 'גיחות') + ' בשבוע'; },
    allDocumented: 'כל הגיחות בסילבוס תועדו',

    /* flight hours in settings */
    hoursTitle: 'שעות טיסה', hoursLogged: 'מתועדות ביומן', hoursManual: 'תוספת ידנית', hoursTotal: 'סך השעות שלך',
    hoursInput: 'סך שעות הטיסה שלך', hoursInputHint: 'למשל 32.5 או 32:30',
    hoursHint: 'השעות מחושבות מדקות הטיסה שתיעדת בכל תחקיר. אם טסת לפני שהתחלת לתעד כאן, או שחסרות דקות בחלק מהטיסות, אפשר לעדכן את הסך. הטיסות עצמן לא משתנות, וכל טיסה חדשה תתווסף לסך הזה.',
    hoursSave: 'עדכון הסך', hoursReset: 'חזרה לשעות מהיומן', hoursSaved: 'סך שעות הטיסה עודכן', hoursResetDone: 'חזרנו לשעות שמתועדות ביומן',
    hoursInvalid: 'צריך מספר שעות בין 0 ל־9999, למשל 32.5 או 32:30',
    hoursWithManual: function (h) { return 'כולל ' + h + ' ידניות'; }, hoursCorrected: 'אחרי תיקון ידני',
    hoursSettingsSub: function (total, adjusted) { return total + ' שעות' + (adjusted ? ' · כולל עדכון ידני' : ' · לפי היומן'); },

    /* motion, touch and home */
    motionTitle: 'תנועה ותחושה', motionLabel: 'אנימציות',
    motionAuto: 'לפי הטלפון', motionFull: 'מלאות', motionReduced: 'מופחתות', motionOff: 'כבויות',
    motionHint: 'מופחתות: רק מעברים קצרים, בלי אפקטים ברקע. לפי הטלפון: כבויות אם הטלפון מוגדר להפחתת תנועה.',
    hapticsLabel: 'רטט בלחיצה', hapticsHint: 'באנדרואיד. באייפון הדפדפן לא מאפשר רטט.',
    homeSectionsTitle: 'מסך הבית', homeSectionsHint: 'הנתונים והטיסה הבאה מוצגים תמיד. את השאר אפשר להסתיר.',
    homeShowFocus: 'הדגש האישי', homeShowQuick: 'קיצורי דרך', homeShowGoals: 'יעדים פתוחים', homeShowRecent: 'טיסות אחרונות',
    shownOnHome: 'מוצג', hiddenFromHome: 'מוסתר',

    /* the update message and its tour */
    releaseVersion: function (v) { return 'גרסה ' + String(v).replace(/^v/, ''); },
    releaseKicker: 'עדכון חדש',
    releaseHighlights: [
      ['clock', 'שעות הטיסה שלך במבט אחד', 'כל הדקות שכבר תיעדת מחושבות לסך שעות, עם גרף של השבועות האחרונים.'],
      ['target', 'היעדים והסולו על המסך הראשון', 'מדדים עם טבעות התקדמות, בלי לגלול.'],
      ['settings', 'שליטה מלאה בהגדרות', 'עדכון ידני של שעות הטיסה, רמת האנימציות, רטט ומה יופיע במסך הבית.'],
      ['layers', 'עיצוב חדש לגמרי', 'כרטיסי זכוכית, מספרים מתגלגלים וקיצורי דרך למסלול, לסילבוס ולגיבוי.']
    ],
    releaseSafe: 'הטיסות, הטיוטות, המחברת והיעדים שלך עברו בדיוק כמו שהם.',
    releaseTour: 'הראו לי מה חדש', releaseLater: 'הבנתי, אולי אחר כך',
    tourLabel: 'סיור במה שחדש', tourNext: 'הבא', tourBack: 'הקודם', tourSkip: 'דילוג', tourDone: 'סיום',
    tourStep: function (i, n) { return i + ' מתוך ' + n; },
    tourSteps: [
      ['.flightcard', 'שעות הטיסה שלך', 'כל הדקות שתיעדת בתחקירים מתחברות כאן לסך שעות. הקו מראה כמה טסת בכל שבוע בחודשיים האחרונים.'],
      ['.readouts--tiles', 'שלושה מדדים לדרך', 'טיסות מתוחקרות, אחוז היעדים שהשגת ואישורי הסולו של השבוע, עם טבעת התקדמות.'],
      ['.qa', 'קיצורי דרך', 'המסלול שלך בקורס, הסילבוס, סיכום השבוע וגיבוי, בלחיצה אחת.'],
      ['.tab--primary .tab__ic', 'תדריך חדש מכל מסך', 'הכפתור המרכזי פותח תדריך. אחרי הנחיתה משלימים אותו לתחקיר.'],
      ['.topbar a[href="#/settings"]', 'הכל ניתן להתאמה', 'בהגדרות אפשר לעדכן את סך שעות הטיסה, לבחור ערכת נושא ואנימציות, ולקבוע מה יופיע במסך הבית.']
    ]
  });
})(window);
